# Generated by Django 5.2.12 on 2026-07-14 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_order_payment_id_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_a87c6f_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_created_at_idx',
            old_name='orders_orde_created_0e92de_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
    ]
